# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug 
      uptimeTag:
        description: 'Uptime Tag to build'
        required: false
        default: 'latest'
        type: string
      relTag:
        description: 'Release Tag'
        required: true
        default: 'debug'
        type: string
      push:
        description: 'Push on Docker Hub'
        required: false
        default: false
        type: boolean
#      environment:
#        description: 'Environment to run tests against'
#        type: environment
#        required: true 

#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]


jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
#        node-version: [14.x, 16.x]
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        repository: louislam/uptime-kuma
        if: ${{ github.event.inputs.uptimeTag != 'latest' }}
        ref: ${{ github.event.inputs.uptimeTag }} 
#        path: _main_
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
#    - run: npm ci
    - run: dir 
    - run: npm install npm -g
#    - run: cd uptime-kuma
#    - run: npm run setup
    - run: npm ci --production
    - run: npm run download-dist
    - run: dir
    - name: zip everything...
      uses: thedoctor0/zip-release@main
      with:
        filename: 'release-win.zip'
        path: '.'
        type: 'zip'
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: "release-win.zip"
        tag_name: ${{ github.event.inputs.relTag }}
          
                  

